feat:test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,7 +7,7 @@ on:
       - main
 
 jobs:
-  backtest:
+  back-test:
     runs-on: ubuntu-latest
 
     services:
@@ -67,16 +67,166 @@ jobs:
         working-directory: ./mock-test
         run: npm test
 
-  fronttest:
+  front-test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Install dependencies of backend
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+
+      - name: Install dependencies of bfrontend
         working-directory: ./todo_list
         run: npm i
 
       - name: Run Test of backend
         working-directory: ./todo_list
         run: npm test
+
+  test_node:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Add SSH key
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{ secrets.EC2_KEY }}
+
+      - name: Ensure SSH directory exists
+        run: |
+          mkdir -p ~/ .ssh
+          chmod 700 ~/ .ssh
+
+      - name: Add SSH known hosts
+        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+
+      - name:
+          test node
+          # run: ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} 'source ~/.bashrc && nvm -v'  ##---> 이전에 설치한것을 읽지 못함
+        run: |
+          ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} '
+          export NVM_DIR="$HOME/.nvm"
+          if [ -s "$NVM_DIR/nvm.sh" ]; then
+            . "$NVM_DIR/nvm.sh"
+          else
+            echo "nvm.sh not found"
+            exit 1
+          fi
+
+          nvm -v
+          nvm use --lts
+          node -v
+          npm -v'
+
+  test_mysql:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Add SSH key
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{ secrets.EC2_KEY }}
+
+      - name: Ensure SSH directory exists
+        run: |
+          mkdir -p ~/ .ssh
+          chmod 700 ~/ .ssh
+
+      - name: Add SSH known hosts
+        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+
+      - name: check mysql
+        run: |
+          ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} '
+          sudo service mysql status'
+
+      - name: test mysql user
+        run: |
+          ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} '
+          mysql -u ${{ secrets.MYSQL_USER}} -p${{ secrets.MYSQL_PASSWORD }} -e "SHOW DATABASES;"'
+
+  deploy_backend:
+    needs:
+      - back-test
+      - front-test
+      - test_node
+      - test_mysql
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout repository
+        uses: actions/checkout@v4
+
+      - name: Add SSH key
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{ secrets.EC2_KEY }}
+
+      - name: Ensure SSH directory exists
+        run: |
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
+
+      - name: Add SSH known hosts
+        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+
+      - name: Install Dependencies of Back
+        working-directory: ./backend
+        run: npm i
+
+      - name: delete map
+        working-directory: ./front/build/
+        run: |
+          rm -rf ./**/*/*.map
+
+      - name: Copy Files to EC2
+        run: |
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            rm -rf /var/www/backend
+            mkdir /var/www/backend'
+          rsync -avz -e "ssh" ./backend/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend
+          rsync -avz -e "ssh" ./backend/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/package.json
+          rsync -avz -e "ssh" ./backend/uploads ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend
+
+      - name: Install and Configure Node.js and PM2
+        run: |
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else 
+              echo "nvm.sh not found"
+              exit 1
+            fi
+            nvm use --lts
+            cd /var/www/backend
+            npm i --production 
+            echo COOKIE="${{ secrets.COOKIE }}" > /var/www/backend/.env
+            echo SESSION="${{ secrets.SESSION }}" >> /var/www/backend/.env
+            echo PORT="${{ secrets.PORT}}" >> /var/www/backend/.env
+            echo MONGURL="${{ secrets.MONGURL }}" >> /var/www/backend/.env
+            echo IV="${{ secrets.IV }}" >> /var/www/backend/.env
+            echo SALT="${{ secrets.SALT }}" >> /var/www/backend/.env
+            echo KEY="${{ secrets.KEY  }}" >> /var/www/backend/.env'
+
+      - name: Start Server
+        run: |
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else 
+              echo "nvm.sh not found"
+              exit 1
+            fi
+            nvm use --lts
+            npm install -g pm2
+            pm2 stop all
+            pm2 start /var/www/backend/src/server.js --name backend
+          '
